language: java
script:
  -"mvn clean install -B"
env:
  global:
   - secure: "MGrYW4n/wiys4F/8G5ZwmSSZk11nz6zROT0mG2a1v6YUe/0opWIesFQGvVAV+NbiAvJ8nJ22DmuOIyH/H5FIQDlr1rILB1eUOYXp6Lvvm2+gO25dR7XkJLDFwemJSyH67alXJpwH8oTZakaQbltX/k+KarVHBX8olESnDDmq0oY="

addons:
  coverity_scan:
    project:
      name: "maxbraun/job-profiles"
      description: "A Jenkins plugin which enables jenkins to generate job from templates automatically — Edit"
    notification_email: me+github@max-braun.com
    build_command: "mvn clean install -B"
    branch_pattern: master
