env:
  global:
   - secure: "MGrYW4n/wiys4F/8G5ZwmSSZk11nz6zROT0mG2a1v6YUe/0opWIesFQGvVAV+NbiAvJ8nJ22DmuOIyH/H5FIQDlr1rILB1eUOYXp6Lvvm2+gO25dR7XkJLDFwemJSyH67alXJpwH8oTZakaQbltX/k+KarVHBX8olESnDDmq0oY="

language: java
script: "mvn clean install -B"

addons:
  coverity_scan:
    project:
      name: "maxbraun/job-profiles"
      description: "Your project description here"
    notification_email: me+github@max-braun.com
    build_command_prepend:
    build_command:"mvn clean install -B"
    branch_pattern: coverity_scan
