env:
  global:
   - secure: "ffpGQc0UnlzZRWf8RxffNhhwq8QlccP2le6ySdiy2aupE3qvlx7y8tuwE1lwwyQHkDznstXdjRX+lUz/rEy8b8U0fXOxMLCBcNc4qMnHnIoZ2dxa0i27vF22Vk/bMlAyqb/08+6IAkBuFvelG0trvs71RMvq+J9mfjOxjK+JoEA="


language: java

  
notifications:
  email:
    - dvyas@coverity.com
  on_success: always
  on_failure: always
  
install:
  - mvn package
  - mvn javadoc:javadoc

addons:
  coverity_scan:
    project:
      name: "maxbraun/job-profiles"
      description: "Your project description here"
    notification_email: dvyas@coverity.com
    build_command: "mvn clean compile"
    branch_pattern: master
    
    
